### ISSUE TITLE
The conversationSignature is not set and is required to ensure that you have permission to use our APIs IsAuthenticated=False. AppID=

### ISSUE THREAD

**Issue by IceCream0910** [transitive-bullshit/bing-chat#22]
When I send a message, I will see a message like the title and no response will be returned. If I send BING's current cookie again, it works, but soon after I get the same error. It seems that BING's cookie expires, is there any way to renew it automatically?

**Comment by PeterNjeim** [comment]
you need `KievRPSSecAuth` in addition to `_U`, separate the two key-value pairs with a semicolon, like : `KievRPSSecAuth=stuff;_U=stuff`
