### ISSUE TITLE
Is is working ?

### ISSUE THREAD

**Issue by x4080** [transitive-bullshit/bing-chat#31]
Hi, I just found out this repo and I can't make it work, I got the cookie from edge by visiting https://www.bing.com
and in dev tools - applications - cookies for https://www.bing.com get the _U cookie, but when I run the example :
```
const res = await api.sendMessage('Write a 500 word essay on frogs.', {
        // change the variant to 'Precise'
        variant: 'Creative'
      })

    // print the full text at the end
    console.log(res)
```

it just finished up quickly with
```
{
  author: 'bot',
  id: '04119b41-7338-48b4-84dd-9b0e2d543964',
  conversationId: undefined,
  clientId: undefined,
  conversationSignature: undefined,
  invocationId: '2',
  text: ''
}
```

Is there anything I missing ?

TIA

**Comment by SpaceSaver** [comment]
Same problem, so far it randomly worked once

**Comment by onarbf** [comment]
For me works well, only breaks up when I add the variant.

**Comment by PeterNjeim** [comment]
you need `KievRPSSecAuth` in addition to `_U`, separate the two key-value pairs with a semicolon, like: `KievRPSSecAuth=stuff;_U=stuff`

**Comment by koji** [comment]
Yes, it works without `variant`

**Comment by x4080** [comment]
@PeterNjeim thanks, sorry for late reply. I'll try it.

@koji, so I should remove the variant ? Should I still use @PeterNjeim advice too ? Thanks

**Comment by koji** [comment]
@x4080 if you use `variant`, I'd recommend you to try to run your code without it since my code started working as expected after removing it.
i wrote a simple api server with express + typescript and called the api from a react app.

**Comment by x4080** [comment]
Thanks @koji I'll try it

**Comment by x4080** [comment]
Ok, i have time to play with it and found out that works :
- not using variant, thanks to @koji 
- and using
```
you need KievRPSSecAuth in addition to _U, separate the two key-value pairs with a semicolon, like: KievRPSSecAuth=stuff;_U=stuff
```

thanks to @PeterNjeim 

The KievRPSSecAuth make it more consistent, without it some time not working

Edit :
variant working if in onProgress mode ex :
```
 const res = await api.sendMessage('Write a 500 word essay on frogs.', {
        variant: 'Creative',
        // print the partial response as the AI is "typing"
        onProgress: (partialResponse) => console.log(partialResponse.text)
    })
```
and not in simple sendMessage
